"""add company to doctors

Revision ID: 97f82ecab18d
Revises: 2a936c22c90d
Create Date: 2026-03-22 12:27:43.386921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f82ecab18d'
down_revision: Union[str, None] = '2a936c22c90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'company')
    # ### end Alembic commands ###
